#!/bin/sh

set -e
set -x

if test -z "$VIRTUAL_ENV"; then
  virtualenv ci-build-venv
  . ci-build-venv/bin/activate
  python setup.py develop
fi

if test -z "$DISPLAY"; then
  # actual CI - will install tests dependencies automatically
  python setup.py test
else
  # in a development workstation, this will produce shorter/nicer output, but
  # requires the test dependencies to be installed manually (or by running
  # `python setup.py test` before).
  python -m unittest lava_tool.tests.test_suite
fi

./integration-tests
