#!/bin/sh

set -e
set -x

if test -z "$VIRTUAL_ENV"; then
  virtualenv ci-build-venv
  . ci-build-venv/bin/activate
  python setup.py develop
fi

python -m unittest lava_tool.tests.test_suite

./integration-tests
