#!/bin/sh

set -e

python -m unittest discover /usr/lib/python2.7/dist-packages/lava -v
python -m unittest discover /usr/lib/python2.7/dist-packages/lava_tool -v
python -m unittest discover /usr/lib/python2.7/dist-packages/lava_dashboard_tool -v
python -m unittest discover /usr/lib/python2.7/dist-packages/lava_scheduler_tool -v
